version: '3.8'

services:
  app:
    build: ./
    container_name: fastapt-app
    networks:
      - intranet
    volumes:
      - ./app:/code/app
    ports:
      - "8080:8000"

networks:
  intranet:
    driver: bridge

volumes:
  postgres_data:
  mariadb_data:

