version: '3.8'

services:
  app:
    build: ./
    container_name: rag-app
    networks:
      - intranet
    volumes:
      - ./app:/code/app
    ports:
      - "22:22"

networks:
  intranet:
    driver: bridge

